 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

model:
  arch: instruct_vicuna7b
  load_finetuned: False
  load_pretrained: True

  pretrained: "https://storage.googleapis.com/sfr-vision-language-research/LAVIS/models/InstructBLIP/instruct_blip_vicuna7b_trimmed.pth"
  finetuned: ""

  vit_model: "clip_vit_g"  # clip_vit_u, clip_vit_m
  vit_model_path: "/xxx/pretrain-models/eva_vit_g.pth"


  # vit encoder
  image_size: 224
  drop_path_rate: 0
  use_grad_checkpoint: False
  vit_precision: "fp16"
  freeze_vit: True
  # graph 
  graph_layers_num: 1
  video_frames: 8
  sim_th: 0.5

  # Q-Former
  num_query_token: 32

  # input text
  max_txt_len: 128
  max_output_txt_len: 256

  # path to Vicuna checkpoint
  llm_model: "./llm/vicuna-7b"

  # generation configs
  prompt: ""


preprocess:
    vis_processor:
        train:
          name: "blip2_image_train"
          image_size: 224
        eval:
          name: "blip_image_eval"
          image_size: 224
    text_processor:
        train:
          name: "blip_caption"
        eval:
          name: "blip_caption"
